 export const GET_DOCTOR_DATA_START = "GET_DOCTOR_DATA_START"
 export const GET_DOCTOR_DATA_SUCCESS = "GET_DOCTOR_DATA_SUCCESS"
 export const GET_DOCTOR_DATA_ERROR = "GET_DOCTOR_DATA_ERROR"

 export const POST_DOCTOR_DATA_START = "POST_DOCTOR_DATA_START"
 export const POST_DOCTOR_DATA_SUCCESS ="POST_DOCTOR_DATA_SUCCESS"
 export const POST_DOCTOR_DATA_ERROR = "POST_DOCTOR_DATA_ERROR"

 export const PUT_DOCTOR_DATA_START = "PUT_DOCTOR_DATA_START"
 export const PUT_DOCTOR_DATA_SUCCESS = "PUT_DOCTOR_DATA_SUCCESS"
 export const PUT_DOCTOR_DATA_ERROR = "PUT_DOCTOR_DATA_ERROR"

 export const DELETE_DOCTOR_DATA_START = "DELETE_DOCTOR_DATA_START"
 export const DELETE_DOCTOR_DATA_SUCCESS = "DELETE_DOCTOR_DATA_SUCCESS"
 export const DELETE_DOCTOR_DATA_ERROR = "DELETE_DOCTOR_DATA_ERROR"

 export const GET_APPOINTMENT_DATA_START = "GET_APPOINTMENT_DATA_START"
 export const GET_APPOINTMENT_DATA_SUCCESS = "GET_APPOINTMENT_DATA_SUCCESS"
 export const GET_APPOINTMENT_DATA_ERROR = "GET_APPOINTMENT_DATA_ERROR"

 export const POST_APPOINTMENT_DATA_START = "POST_APPOINTMENT_DATA_START"
 export const POST_APPOINTMENT_DATA_SUCCESS = "POST_APPOINTMENT_DATA_SUCCESS"
 export const POST_APPOINTMENT_DATA_ERROR = "POST_APPOINTMENT_DATA_ERROR"